//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace w2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("w2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G 57
        ///A 71
        ///S 87
        ///P 97
        ///V 99
        ///T 101
        ///C 103
        ///I 113
        ///L 113
        ///N 114
        ///D 115
        ///K 128
        ///Q 128
        ///E 129
        ///M 131
        ///H 137
        ///F 147
        ///R 156
        ///Y 163
        ///W 186.
        /// </summary>
        internal static string integer_mass_table {
            get {
                return ResourceManager.GetString("integer_mass_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M Met
        ///H His
        ///Q Gln
        ///P Pro
        ///R Arg
        ///L Leu
        ///D Asp
        ///E Glu
        ///A Ala
        ///G Gly
        ///V Val
        ///Y Tyr
        ///* XXX
        ///S Ser
        ///C Cys
        ///W Trp
        ///F Phe
        ///L Leu
        ///N Asn
        ///K Lys
        ///T Thr
        ///S Ser
        ///R Arg
        ///I Ile
        ///
        ///.
        /// </summary>
        internal static string RNA_codon_ext {
            get {
                return ResourceManager.GetString("RNA_codon_ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAA K
        ///AAC N
        ///AAG K
        ///AAU N
        ///ACA T
        ///ACC T
        ///ACG T
        ///ACU T
        ///AGA R
        ///AGC S
        ///AGG R
        ///AGU S
        ///AUA I
        ///AUC I
        ///AUG M
        ///AUU I
        ///CAA Q
        ///CAC H
        ///CAG Q
        ///CAU H
        ///CCA P
        ///CCC P
        ///CCG P
        ///CCU P
        ///CGA R
        ///CGC R
        ///CGG R
        ///CGU R
        ///CUA L
        ///CUC L
        ///CUG L
        ///CUU L
        ///GAA E
        ///GAC D
        ///GAG E
        ///GAU D
        ///GCA A
        ///GCC A
        ///GCG A
        ///GCU A
        ///GGA G
        ///GGC G
        ///GGG G
        ///GGU G
        ///GUA V
        ///GUC V
        ///GUG V
        ///GUU V
        ///UAA 
        ///UAC Y
        ///UAG 
        ///UAU Y
        ///UCA S
        ///UCC S
        ///UCG S
        ///UCU S
        ///UGA 
        ///UGC C
        ///UGG W
        ///UGU C
        ///UUA L
        ///UUC F
        ///UUG L
        ///UUU F.
        /// </summary>
        internal static string RNA_codon_table {
            get {
                return ResourceManager.GetString("RNA_codon_table", resourceCulture);
            }
        }
    }
}
